"""hostname not unique

Revision ID: 5f99b898af5f
Revises: f8403cadc21b
Create Date: 2024-03-01 10:40:44.521492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f99b898af5f'
down_revision = 'f8403cadc21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_discovered_devices_ipv4')
        batch_op.create_index(batch_op.f('ix_discovered_devices_ipv4'), ['ipv4'], unique=True)

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index('ix_hosts_hostname')
        batch_op.create_index(batch_op.f('ix_hosts_hostname'), ['hostname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_hostname'))
        batch_op.create_index('ix_hosts_hostname', ['hostname'], unique=1)

    with op.batch_alter_table('discovered_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_devices_ipv4'))
        batch_op.create_index('ix_discovered_devices_ipv4', ['ipv4'], unique=False)

    # ### end Alembic commands ###
